#!/bin/bash

LIB_NAME="site_analizer"
EXT="pth"
SITE_PACKAGES=$(python3 -c 'import site; print(site.getsitepackages()[0])')
PTH_PATH="$SITE_PACKAGES/$LIB_NAME.$EXT"
LIB_PATH="$(pwd)/lib"

pip install img2pdf numpy opencv-python opencv-contrib-python BeautifulSoup4 pillow chardet requests

sudo echo $LIB_PATH > $PTH_PATH

if [ $? -eq 0 ] ; then
    echo "Installed"
else
    echo "Error"
fi

